
services:
  web:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "1010:80"

    volumes:
      - ./www:/html
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

